edition = "2024"
max_width = 100
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
imports_granularity = "Crate"
force_multiline_blocks = true
format_strings = true
reorder_modules = true
use_field_init_shorthand = false
use_try_shorthand = false
wrap_comments = true
